from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(892, 729)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.fillcolorbucketbutton = QtWidgets.QPushButton(self.centralwidget)
        self.fillcolorbucketbutton.setText("")
        self.fillcolorbucketbutton.setObjectName("fillcolorbucketbutton")
        self.gridLayout_3.addWidget(self.fillcolorbucketbutton, 0, 1, 1, 1)
        self.palletebutton = QtWidgets.QPushButton(self.centralwidget)
        self.palletebutton.setText("")
        self.palletebutton.setObjectName("palletebutton")
        self.gridLayout_3.addWidget(self.palletebutton, 0, 2, 1, 1)
        self.pencilbutton = QtWidgets.QPushButton(self.centralwidget)
        self.pencilbutton.setText("")
        self.pencilbutton.setObjectName("pencilbutton")
        self.gridLayout_3.addWidget(self.pencilbutton, 0, 0, 1, 1)
        self.rubberbutton = QtWidgets.QPushButton(self.centralwidget)
        self.rubberbutton.setText("")
        self.rubberbutton.setObjectName("rubberbutton")
        self.gridLayout_3.addWidget(self.rubberbutton, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.roundedrectanglebutton = QtWidgets.QPushButton(self.centralwidget)
        self.roundedrectanglebutton.setText("")
        self.roundedrectanglebutton.setObjectName("roundedrectanglebutton")
        self.gridLayout_2.addWidget(self.roundedrectanglebutton, 0, 1, 1, 1)
        self.fivepstarbutton = QtWidgets.QPushButton(self.centralwidget)
        self.fivepstarbutton.setText("")
        self.fivepstarbutton.setObjectName("fivepstarbutton")
        self.gridLayout_2.addWidget(self.fivepstarbutton, 2, 1, 1, 1)
        self.sixpstarbutton = QtWidgets.QPushButton(self.centralwidget)
        self.sixpstarbutton.setText("")
        self.sixpstarbutton.setObjectName("sixpstarbutton")
        self.gridLayout_2.addWidget(self.sixpstarbutton, 2, 2, 1, 1)
        self.righttrianglebutton = QtWidgets.QPushButton(self.centralwidget)
        self.righttrianglebutton.setText("")
        self.righttrianglebutton.setObjectName("righttrianglebutton")
        self.gridLayout_2.addWidget(self.righttrianglebutton, 2, 0, 1, 1)
        self.rectanglebutton = QtWidgets.QPushButton(self.centralwidget)
        self.rectanglebutton.setText("")
        self.rectanglebutton.setObjectName("rectanglebutton")
        self.gridLayout_2.addWidget(self.rectanglebutton, 0, 0, 1, 1)
        self.trianglebutton = QtWidgets.QPushButton(self.centralwidget)
        self.trianglebutton.setText("")
        self.trianglebutton.setObjectName("trianglebutton")
        self.gridLayout_2.addWidget(self.trianglebutton, 0, 2, 1, 1)
        self.initialfivepstarbutton = QtWidgets.QPushButton(self.centralwidget)
        self.initialfivepstarbutton.setText("")
        self.initialfivepstarbutton.setObjectName("initialfivepstarbutton")
        self.gridLayout_2.addWidget(self.initialfivepstarbutton, 3, 1, 1, 1)
        self.filroundedrectanglebutton = QtWidgets.QPushButton(self.centralwidget)
        self.filroundedrectanglebutton.setText("")
        self.filroundedrectanglebutton.setObjectName("filroundedrectanglebutton")
        self.gridLayout_2.addWidget(self.filroundedrectanglebutton, 4, 1, 1, 1)
        self.filtrianglebutton = QtWidgets.QPushButton(self.centralwidget)
        self.filtrianglebutton.setText("")
        self.filtrianglebutton.setObjectName("filtrianglebutton")
        self.gridLayout_2.addWidget(self.filtrianglebutton, 4, 2, 1, 1)
        self.initialsixpstarbutton = QtWidgets.QPushButton(self.centralwidget)
        self.initialsixpstarbutton.setText("")
        self.initialsixpstarbutton.setObjectName("initialsixpstarbutton")
        self.gridLayout_2.addWidget(self.initialsixpstarbutton, 3, 2, 1, 1)
        self.filrighttrianglebutton = QtWidgets.QPushButton(self.centralwidget)
        self.filrighttrianglebutton.setText("")
        self.filrighttrianglebutton.setObjectName("filrighttrianglebutton")
        self.gridLayout_2.addWidget(self.filrighttrianglebutton, 3, 0, 1, 1)
        self.filrectanglebutton = QtWidgets.QPushButton(self.centralwidget)
        self.filrectanglebutton.setText("")
        self.filrectanglebutton.setObjectName("filrectanglebutton")
        self.gridLayout_2.addWidget(self.filrectanglebutton, 4, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBoxWidth = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxWidth.sizePolicy().hasHeightForWidth())
        self.comboBoxWidth.setSizePolicy(sizePolicy)
        self.comboBoxWidth.setMinimumSize(QtCore.QSize(50, 50))
        self.comboBoxWidth.setObjectName("comboBoxWidth")
        self.horizontalLayout_2.addWidget(self.comboBoxWidth)
        self.pushButtonWhite = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonWhite.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButtonWhite.setText("")
        self.pushButtonWhite.setObjectName("pushButtonWhite")
        self.horizontalLayout_2.addWidget(self.pushButtonWhite)
        self.pushButtonBlack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBlack.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButtonBlack.setText("")
        self.pushButtonBlack.setObjectName("pushButtonBlack")
        self.horizontalLayout_2.addWidget(self.pushButtonBlack)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.colorbuttongroup = QtWidgets.QButtonGroup(MainWindow)
        self.colorbuttongroup.setObjectName("colorbuttongroup")
        self.colorbuttongroup.addButton(self.pushButton)
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.colorbuttongroup.addButton(self.pushButton_10)
        self.gridLayout.addWidget(self.pushButton_10, 1, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.colorbuttongroup.addButton(self.pushButton_2)
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.colorbuttongroup.addButton(self.pushButton_11)
        self.gridLayout.addWidget(self.pushButton_11, 1, 4, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.colorbuttongroup.addButton(self.pushButton_5)
        self.gridLayout.addWidget(self.pushButton_5, 0, 4, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.colorbuttongroup.addButton(self.pushButton_3)
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.colorbuttongroup.addButton(self.pushButton_4)
        self.gridLayout.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.colorbuttongroup.addButton(self.pushButton_12)
        self.gridLayout.addWidget(self.pushButton_12, 1, 5, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.colorbuttongroup.addButton(self.pushButton_6)
        self.gridLayout.addWidget(self.pushButton_6, 0, 5, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.colorbuttongroup.addButton(self.pushButton_8)
        self.gridLayout.addWidget(self.pushButton_8, 1, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.colorbuttongroup.addButton(self.pushButton_7)
        self.gridLayout.addWidget(self.pushButton_7, 1, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.colorbuttongroup.addButton(self.pushButton_9)
        self.gridLayout.addWidget(self.pushButton_9, 1, 2, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.changingcolbuttongroup = QtWidgets.QButtonGroup(MainWindow)
        self.changingcolbuttongroup.setObjectName("changingcolbuttongroup")
        self.changingcolbuttongroup.addButton(self.pushButton_13)
        self.gridLayout.addWidget(self.pushButton_13, 2, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.changingcolbuttongroup.addButton(self.pushButton_14)
        self.gridLayout.addWidget(self.pushButton_14, 2, 1, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.changingcolbuttongroup.addButton(self.pushButton_15)
        self.gridLayout.addWidget(self.pushButton_15, 2, 2, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setText("")
        self.pushButton_16.setObjectName("pushButton_16")
        self.changingcolbuttongroup.addButton(self.pushButton_16)
        self.gridLayout.addWidget(self.pushButton_16, 2, 3, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.changingcolbuttongroup.addButton(self.pushButton_17)
        self.gridLayout.addWidget(self.pushButton_17, 2, 4, 1, 1)
        self.setcolorbutton = QtWidgets.QPushButton(self.centralwidget)
        self.setcolorbutton.setText("")
        self.setcolorbutton.setObjectName("setcolorbutton")
        self.gridLayout.addWidget(self.setcolorbutton, 2, 5, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 3, 1, 1)
        self.paintgridLayout = QtWidgets.QGridLayout()
        self.paintgridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.paintgridLayout.setContentsMargins(-1, 0, -1, -1)
        self.paintgridLayout.setObjectName("paintgridLayout")
        self.gridLayout_5.addLayout(self.paintgridLayout, 1, 0, 1, 4)
        self.horizontalLayout.addLayout(self.gridLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 892, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.action_brush = QtWidgets.QAction(MainWindow)
        self.action_brush.setObjectName("action_brush")
        self.action_line = QtWidgets.QAction(MainWindow)
        self.action_line.setObjectName("action_line")
        self.action_circle = QtWidgets.QAction(MainWindow)
        self.action_circle.setObjectName("action_circle")
        self.action_helptext = QtWidgets.QAction(MainWindow)
        self.action_helptext.setObjectName("action_helptext")
        self.action_modulestext = QtWidgets.QAction(MainWindow)
        self.action_modulestext.setObjectName("action_modulestext")
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.toolBar.addAction(self.action_line)
        self.toolBar.addAction(self.action_brush)
        self.toolBar.addAction(self.action_circle)
        self.menu.addAction(self.action_brush)
        self.menu.addAction(self.action_line)
        self.menu.addAction(self.action_circle)
        self.menu_2.addAction(self.action_helptext)
        self.menu_2.addAction(self.action_modulestext)
        self.menu_3.addAction(self.action_open)
        self.menu_3.addAction(self.action_save)
        self.menu_3.addAction(self.action_exit)
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Графический редактор"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menu.setTitle(_translate("MainWindow", "Инструменты"))
        self.menu_2.setTitle(_translate("MainWindow", "Помощь"))
        self.menu_3.setTitle(_translate("MainWindow", "Файл"))
        self.action_brush.setText(_translate("MainWindow", "Кисть"))
        self.action_line.setText(_translate("MainWindow", "Линия"))
        self.action_circle.setText(_translate("MainWindow", "Круг"))
        self.action_helptext.setText(_translate("MainWindow", "О программе"))
        self.action_modulestext.setText(_translate("MainWindow", "Используемые модули"))
        self.action_open.setText(_translate("MainWindow", "Открыть файл"))
        self.action_save.setText(_translate("MainWindow", "Сохранить файл"))
        self.action_exit.setText(_translate("MainWindow", "Выход"))
